### ISSUE TITLE
 security exception thrown

### ISSUE THREAD

**Issue by AndroidStdio** [SanjayDevTech/Screen-Recorder#2]
After update to android 10, It gets a  security exception thrown. 
Caused by: java.lang.SecurityException: Media projections require a foreground service of type ServiceInfo.FOREGROUND_SERVICE_TYPE_MEDIA_PROJECTION
 
mMediaProjection = mProjectionManager.getMediaProjection(resultCode, data);

would you know by any chance how to fix this?

**Comment by SanjayDevTech** [comment]
Oh yes... Due to new security features in Android 10, you need to set foreground service before starting media projection.
Anyway thank you for letting me know.
I will update this repository soon...

**Comment by AndroidStdio** [comment]
Hey Sanjay,
Have you found the solution yet?

**Comment by SanjayDevTech** [comment]
@AndroidStdio I tried my best and solved major problems...
But still the error happens.. I will solve ASAP

**Comment by Raj123456788** [comment]
@SanjayDevTech : Can anyone solve this?

**Comment by SanjayDevTech** [comment]
@AndroidStdio @Raj123456788 Sorry for this late.
I got time to solve this issue, importantly I found the cause.
Now you can run this code in latest versions of Android including Android 12.
